version: "3.9"

services:

  database:
    image: postgres:alpine3.18
    container_name: ft_transcendence_database
    env_file:
      - .env
    restart: always
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 10s
      retries: 10
  
  backend:
    build: ./backend/
    container_name: ft_transcendence_backend
    restart: always
    env_file:
      - .env
    ports:
      - 3001:3001
      - 5555:5555
    environment:
      - IP_ADDRESS=${IP_ADDRESS}
    depends_on:
      database:
        condition: service_healthy
  
  frontend:
    build: ./frontend/
    container_name: ft_transcendence_frontend
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    environment:
      - IP_ADDRESS=${IP_ADDRESS}